# Generated by Django 5.2.1 on 2025-07-30 06:42

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dalal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(upload_to='dalals/pictures/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('address_last_known', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(max_length=250)),
                ('affiliation', models.TextField()),
                ('profile_report', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('traitor_rank', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('shoe_count', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
