# Generated by Django 5.2.1 on 2025-08-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_district_remove_dalal_city_remove_dalal_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dalal',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('captured', 'Captured'), ('fugitive', 'Fugitive'), ('terminated', 'Terminated'), ('unknown', 'Unknown')], default='unknown', max_length=60),
        ),
    ]
