# Generated by Django 5.2.1 on 2025-08-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_dalal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dalal',
            name='affiliation',
            field=models.CharField(max_length=250),
        ),
    ]
