# Generated by Django 5.2.1 on 2025-08-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_dalal_affiliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dalal',
            old_name='alias',
            new_name='dalal_code',
        ),
        migrations.RemoveField(
            model_name='dalal',
            name='dob',
        ),
        migrations.AlterField(
            model_name='dalal',
            name='affiliation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dalal',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dalals/pictures/'),
        ),
    ]
