# Generated by Django 5.2.1 on 2025-08-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_rename_alias_dalal_dalal_code_remove_dalal_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dalal',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
