# Generated by Django 5.2.1 on 2025-08-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_alter_dalal_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='dalal',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
