# Generated by Django 5.2.1 on 2025-08-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_dalal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dalal',
            name='slug',
        ),
    ]
